# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

executors:
  macos:
    macos:
      xcode: "11.0.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      FL_OUTPUT_DIR: output

jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "11.0.0"

    steps:
      - checkout

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 7
            SCAN_SCHEME: MTC2018

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

  install_cocoapods:
    macos:
      xcode: "11.0.0"
    steps:
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: pod install

workflows:
  version: 2
  build:
    jobs:
      - build

